# Generated by Django 3.0.3 on 2020-02-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=-1.0, upload_to='%Y/%m'),
            preserve_default=False,
        ),
    ]
